# Contents for Python Makefile 
PY = python3

all: server client

# make sure TAs can make server/client/clean
server:
client:
clean:

run-server: server.py
	$(PY) $< 127.0.0.1 9012
run-client: client.py
	$(PY) $< 127.0.0.1 9012